This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./HWThesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file HWThesis.acn....done (20 entries accepted, 0 rejected).
Sorting entries....done (106 comparisons).
Generating output file HWThesis.acr....done (15 lines written, 0 warnings).
Output written in HWThesis.acr.
Transcript written in HWThesis.alg.
